# Generated by Django 5.2.5 on 2025-08-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True),
        ),
    ]
