# Generated by Django 5.2.5 on 2025-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0002_notes_alter_document_document_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
