# Generated by Django 5.2.5 on 2025-08-22 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0004_alter_document_title_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='notes',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
