# Generated by Django 5.2.5 on 2025-08-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0005_highlights_notes_alter_highlights_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notetaker.document'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HighlightNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField()),
                ('notes', models.CharField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notetaker.document')),
            ],
        ),
    ]
