# Generated by Django 5.2.5 on 2025-08-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0006_notes_document_highlightnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlights',
            name='notes',
        ),
    ]
